# -- GEN AI ---

# 1. Gen AI does not understand or comprehend the content it generates.

# 2. Gen AI relies on statistical patterns and correlations learned from the training data.

# --- LARGE LANGUAGE MODELS (LLMs) ---

# 1. text-generating models

# 2. designed to understand and generate human-like text

# --- LLM RESPONSES ---

# 1. The response generated by an LLM is a probabilistic continuation of the instructions recieved. 

# 2. LLM provids the most likely response based on the patterns it has learned from the training data. 

