# -- GEN AI ---

# 1. Gen AI does not understand or comprehend the content it generates.
# 2. Gen AI relies on statistical patterns and correlations learned from the training data.

# --- LARGE LANGUAGE MODELS (LLMs) ---

# 1. text-generating models
# 2. designed to understand and generate human-like text

# --- LLM RESPONSES ---

# 1. The response generated by an LLM is a probabilistic continuation of the instructions recieved. 
# 2. LLM provids the most likely response based on the patterns it has learned from the training data. 

# --- PROMPTS ---

#  1. The LLM will interpret these instructions and return a response based on the patterns it has learned from its training data.

#  --- ACCURACY --- 

#  LLMs are designed to create human-like text and are often fine-tuned to be as helpful as possible, even is that mean occasionally producing plausible-sounding but incorrect information. (hallucinations)

# --- TEMPERATURE ---

# The higher the temperature value, the more random the generated result will become, and the more likely the response will contain false statements.

# A higher temperature may be appropriate when configuring an LLM to respond with more diverse and creative outputs, a lower temperature required when responses should be consistent and precise.
